kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: node-app-mongodb-pvc
  namespace: node-app 
spec:
  storageClassName: my-local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi